import Head from "next/head";
import { Navbar } from "../Navbar";

import styles from "./MainLayout.module.css";

export const MainLayout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>This is the App from world</title>
        <meta name="description" content="Generated by Andres" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>{children}</main>
    </div>
  );
};
